root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/server"
  cmd = "go build -o ./tmp/server ./cmd/server/main.go"
  delay = 1000
  exclude_dir = ["tmp", "vendor", "docs"]
  exclude_regex = ["_test\\.go$"]
  include_ext = ["go", "toml"]
  kill_delay = 500

[log]
  time = false

[color]
  build = "yellow"
  runner = "green"
  main = "magenta"
